//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anchor.FA.Web.AmbulanceService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatientRecordInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PatientRecordInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MeasureInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MeasureInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        private int OrderIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AmbulanceService.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 CNumber 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAmbulance", ReplyAction="*")]
        Anchor.FA.Web.AmbulanceService.GetAmbulanceResponse GetAmbulance(Anchor.FA.Web.AmbulanceService.GetAmbulanceRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 PatientRecordInfo 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SavePatientRecord", ReplyAction="*")]
        Anchor.FA.Web.AmbulanceService.SavePatientRecordResponse SavePatientRecord(Anchor.FA.Web.AmbulanceService.SavePatientRecordRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAmbulanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAmbulance", Namespace="http://tempuri.org/", Order=0)]
        public Anchor.FA.Web.AmbulanceService.GetAmbulanceRequestBody Body;
        
        public GetAmbulanceRequest() {
        }
        
        public GetAmbulanceRequest(Anchor.FA.Web.AmbulanceService.GetAmbulanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAmbulanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CNumber;
        
        public GetAmbulanceRequestBody() {
        }
        
        public GetAmbulanceRequestBody(string CNumber) {
            this.CNumber = CNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAmbulanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAmbulanceResponse", Namespace="http://tempuri.org/", Order=0)]
        public Anchor.FA.Web.AmbulanceService.GetAmbulanceResponseBody Body;
        
        public GetAmbulanceResponse() {
        }
        
        public GetAmbulanceResponse(Anchor.FA.Web.AmbulanceService.GetAmbulanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAmbulanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAmbulanceResult;
        
        public GetAmbulanceResponseBody() {
        }
        
        public GetAmbulanceResponseBody(string GetAmbulanceResult) {
            this.GetAmbulanceResult = GetAmbulanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SavePatientRecordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SavePatientRecord", Namespace="http://tempuri.org/", Order=0)]
        public Anchor.FA.Web.AmbulanceService.SavePatientRecordRequestBody Body;
        
        public SavePatientRecordRequest() {
        }
        
        public SavePatientRecordRequest(Anchor.FA.Web.AmbulanceService.SavePatientRecordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SavePatientRecordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Anchor.FA.Web.AmbulanceService.PatientRecordInfo[] PatientRecordInfo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Anchor.FA.Web.AmbulanceService.MeasureInfo[] MeasureInfo;
        
        public SavePatientRecordRequestBody() {
        }
        
        public SavePatientRecordRequestBody(Anchor.FA.Web.AmbulanceService.PatientRecordInfo[] PatientRecordInfo, Anchor.FA.Web.AmbulanceService.MeasureInfo[] MeasureInfo) {
            this.PatientRecordInfo = PatientRecordInfo;
            this.MeasureInfo = MeasureInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SavePatientRecordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SavePatientRecordResponse", Namespace="http://tempuri.org/", Order=0)]
        public Anchor.FA.Web.AmbulanceService.SavePatientRecordResponseBody Body;
        
        public SavePatientRecordResponse() {
        }
        
        public SavePatientRecordResponse(Anchor.FA.Web.AmbulanceService.SavePatientRecordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SavePatientRecordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SavePatientRecordResult;
        
        public SavePatientRecordResponseBody() {
        }
        
        public SavePatientRecordResponseBody(int SavePatientRecordResult) {
            this.SavePatientRecordResult = SavePatientRecordResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : Anchor.FA.Web.AmbulanceService.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<Anchor.FA.Web.AmbulanceService.Service1Soap>, Anchor.FA.Web.AmbulanceService.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Anchor.FA.Web.AmbulanceService.GetAmbulanceResponse Anchor.FA.Web.AmbulanceService.Service1Soap.GetAmbulance(Anchor.FA.Web.AmbulanceService.GetAmbulanceRequest request) {
            return base.Channel.GetAmbulance(request);
        }
        
        public string GetAmbulance(string CNumber) {
            Anchor.FA.Web.AmbulanceService.GetAmbulanceRequest inValue = new Anchor.FA.Web.AmbulanceService.GetAmbulanceRequest();
            inValue.Body = new Anchor.FA.Web.AmbulanceService.GetAmbulanceRequestBody();
            inValue.Body.CNumber = CNumber;
            Anchor.FA.Web.AmbulanceService.GetAmbulanceResponse retVal = ((Anchor.FA.Web.AmbulanceService.Service1Soap)(this)).GetAmbulance(inValue);
            return retVal.Body.GetAmbulanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Anchor.FA.Web.AmbulanceService.SavePatientRecordResponse Anchor.FA.Web.AmbulanceService.Service1Soap.SavePatientRecord(Anchor.FA.Web.AmbulanceService.SavePatientRecordRequest request) {
            return base.Channel.SavePatientRecord(request);
        }
        
        public int SavePatientRecord(Anchor.FA.Web.AmbulanceService.PatientRecordInfo[] PatientRecordInfo, Anchor.FA.Web.AmbulanceService.MeasureInfo[] MeasureInfo) {
            Anchor.FA.Web.AmbulanceService.SavePatientRecordRequest inValue = new Anchor.FA.Web.AmbulanceService.SavePatientRecordRequest();
            inValue.Body = new Anchor.FA.Web.AmbulanceService.SavePatientRecordRequestBody();
            inValue.Body.PatientRecordInfo = PatientRecordInfo;
            inValue.Body.MeasureInfo = MeasureInfo;
            Anchor.FA.Web.AmbulanceService.SavePatientRecordResponse retVal = ((Anchor.FA.Web.AmbulanceService.Service1Soap)(this)).SavePatientRecord(inValue);
            return retVal.Body.SavePatientRecordResult;
        }
    }
}
